<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findByUser($user){
//        $query = $this->createQueryBuilder('annonce')
//            ->innerJoin('annonce.users','user')
//            ->where('user.id = :userParam')
//            ->setParameter('userParam',$user->getId());
//
//        var_dump($query->getQuery()->getResult());die;
//    }
}
