<?php

namespace AppBundle\Repository;

/**
 * DisponibilitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
