<?php

namespace AppBundle\Repository;

/**
 * ListreqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListreqRepository extends \Doctrine\ORM\EntityRepository
{
}
