<?php

namespace AppBundle\Repository;

/**
 * ParticularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticularRepository extends \Doctrine\ORM\EntityRepository
{
}
