<?php

namespace AppBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findByUser($user){
//        $query = $this->createQueryBuilder('reclamation')
//            ->innerJoin('reclamation.users','user')
//            ->where('user.id = :userParam')
//            ->setParameter('userParam',$user->getId());
//
//        var_dump($query->getQuery()->getResult());die;
//    }
}
