app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check

#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc

# app/config/routing.yml
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin


nelmio:
    resource: "routing/nelmio_api_doc.yml"

login:
    path:     /user/login
    defaults: { _controller: AppBundle:Client:login }


register:
    resource: '@AppBundle/Controller/ClientController.php'
    type: rest
