AppBundle\Entity\Client:
    exclusion_policy: none
    properties:
        id:
            groups: ['client', 'auth-token']
        username:
            groups: ['client', 'auth-token']
        mail:
            groups: ['client', 'auth-token']
        type:
            groups: ['client', 'auth-token']
        password:
            groups : ['client']
