nelmio_api_doc:
    documentation:
        info:
            title: ProMatching
            description: This is an awesome app!
            version: 1.0.0
    routes:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)